name: Prerequisite Engine CI

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]

jobs:
  python-tests:
    name: Python unit tests (prerequisite engine)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sqlalchemy pydantic pytest pytest-asyncio

      - name: Run critical prerequisite engine tests
        run: |
          pytest -q tests/test_prerequisite_engine_core.py



